from flask import Blueprint, request, jsonify
from app.firebase_config import db
from app.utils.event_utils import is_event_over
from difflib import SequenceMatcher

chatbot_bp = Blueprint('chatbot', __name__, url_prefix='/api/chatbot')

# ── FAQ knowledge base ────────────────────────────────────────────────
# Each entry: a list of phrasings that should trigger it, and the answer.
# The bot matches the user's message against ALL phrasings across ALL
# entries and returns the best-scoring answer above a confidence threshold.
FAQ = [
    {
        'patterns': ['what is ems', 'what is this', 'what does this platform do', 'about ems', 'what is this website'],
        'answer': "EMS (Unified Event Lifecycle Management System) is a platform for organizing and attending events end-to-end — creating events, selling tickets, checking in attendees, managing sponsors, and issuing certificates."
    },
    {
        'patterns': ['how do i register', 'how to register for an event', 'how do i sign up for an event', 'how to book a ticket', 'how do i buy a ticket'],
        'answer': "Browse events on the homepage, open the one you're interested in, choose your ticket quantity for each ticket type, and click Proceed to Checkout. If it's a paid ticket you'll be taken to payment; free tickets confirm instantly."
    },
    {
        'patterns': ['how does payment work', 'how do i pay', 'what payment methods', 'is payment secure'],
        'answer': "Payments are processed securely through Razorpay, supporting cards, UPI, netbanking, and wallets. Your payment is verified before your ticket is confirmed."
    },
    {
        'patterns': ['where is my ticket', 'how do i get my qr code', 'i didn\'t receive my ticket', 'lost my ticket'],
        'answer': "After a successful payment, your ticket with QR code is emailed to you and also available anytime under My Tickets in your account."
    },
    {
        'patterns': ['how does check in work', 'how do i check in', 'what happens at the venue'],
        'answer': "Show the QR code from your ticket (email or My Tickets page) to the organizer at the venue — they'll scan it to check you in."
    },
    {
        'patterns': ['how do i use a promo code', 'do you have discount codes', 'how do i apply a coupon'],
        'answer': "On the event page, enter your promo code in the 'Have a promo code?' box before checkout — the discount applies automatically to your total."
    },
    {
        'patterns': ['can i buy multiple tickets', 'can i buy more than one ticket', 'multiple ticket types'],
        'answer': "Yes — you can select quantities for several ticket types in the same order and check out once for all of them."
    },
    {
        'patterns': ['how do i cancel my registration', 'can i cancel my ticket', 'how do i get a refund'],
        'answer': "Go to My Tickets, find your registration under Upcoming, and click Cancel Registration. Your refund amount depends on how close to the event date you cancel — the exact amount is shown before you confirm."
    },
    {
        'patterns': ['how do i get my certificate', 'where is my certificate', 'certificate of attendance'],
        'answer': "Certificates are generated by the organizer after the event ends, for attendees who checked in. Once ready, you'll get a notification and can download it from My Certificates."
    },
    {
        'patterns': ['how do i leave a review', 'can i review an event', 'how do i rate an event'],
        'answer': "Once you've checked in and the event has ended, a Leave a Review button appears on that ticket under the Past tab in My Tickets."
    },
    {
        'patterns': ['how do i become a sponsor', 'sponsor an event', 'exhibitor booth'],
        'answer': "Sponsorship is arranged directly with the event organizer. If you're already listed as a sponsor for an event, you can log in through the sponsor portal to see your details and leads."
    },
    {
        'patterns': ['how do i contact the organizer', 'contact support', 'i need help'],
        'answer': "For event-specific questions, check the event page for organizer details. For account or platform issues, use the Contact link in the footer."
    },
    {
        'patterns': ['how do i create an event', 'how do i organize an event', 'become an organizer'],
        'answer': "Sign up with the organizer role, then go to Events → Create Event to add your event details, venue, and ticket types."
    },
    {
        'patterns': ['how do i join the waitlist', 'ticket is sold out'],
        'answer': "If a ticket type is sold out, a Join Waitlist button appears instead. You'll be notified by email if a spot opens up."
    },
]

CONFIDENCE_THRESHOLD = 0.45


def _similarity(a, b):
    return SequenceMatcher(None, a, b).ratio()


def _best_faq_match(user_message):
    user_message = user_message.lower().strip()
    best_score = 0
    best_answer = None

    for entry in FAQ:
        for pattern in entry['patterns']:
            score = _similarity(user_message, pattern)
            # Boost score if the pattern's key words appear directly in the message
            pattern_words = set(pattern.split())
            message_words = set(user_message.split())
            overlap = len(pattern_words & message_words) / max(len(pattern_words), 1)
            combined = max(score, overlap)

            if combined > best_score:
                best_score = combined
                best_answer = entry['answer']

    return best_answer if best_score >= CONFIDENCE_THRESHOLD else None


def _handle_live_event_lookup(user_message):
    """Handles questions asking what events are currently happening/upcoming."""
    msg = user_message.lower()
    live_keywords = ['what events', 'upcoming events', 'events happening', 'any events', 'events available', 'list events']
    if not any(k in msg for k in live_keywords):
        return None

    docs = (
        db.collection('events')
        .where('status', '==', 'published')
        .order_by('start_datetime')
        .limit(5)
        .stream()
    )

    events = []
    for d in docs:
        data = d.to_dict()
        if not is_event_over(data):
            events.append(data)

    if not events:
        return "There are no upcoming events published right now — check back soon!"

    lines = [f"- {e.get('name')} ({e['start_datetime'].strftime('%b %d, %Y')})" for e in events[:5]]
    return "Here are the next upcoming events:\n" + "\n".join(lines)


@chatbot_bp.route('/ask', methods=['POST'])
def ask():
    data = request.get_json(silent=True) or {}
    user_message = data.get('message', '').strip()

    if not user_message:
        return jsonify({'reply': "Ask me anything about using EMS — registering, tickets, payments, certificates, and more."})

    live_answer = _handle_live_event_lookup(user_message)
    if live_answer:
        return jsonify({'reply': live_answer})

    faq_answer = _best_faq_match(user_message)
    if faq_answer:
        return jsonify({'reply': faq_answer})

    return jsonify({
        'reply': "I'm not sure about that one — I can help with registering, tickets, payments, cancellations, certificates, reviews, and sponsorships. For anything else, please use the Contact link in the footer."
    })